version: '3'

services:
  discord-bot:
    build:
       context: "."
       dockerfile: "./Dockerfile"
    working_dir: /usr/src/bot
    volumes:
      - /home/ubuntu/discord-horse-racing:/usr/src/bot
    depends_on:
      - sqlite3-db
    networks:
      - bot-network
    restart: on-failure

  sqlite3-db:
    image: keinos/sqlite3:latest
    volumes:
      - ./userbalDB.db:/usr/src/bot/userbalDB.db
    networks:
      - bot-network
    restart: on-failure

volumes:
  sqlite-data:

networks:
  bot-network:
